version: "3"

services:
    #redis:
    #    image: "redis"
    #    command: redis-server --requirepass ${REDIS_PASSWORD}
    ##    container_name: redis
    #    networks:
    #        - all

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    main:
        build: .
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        container_name: main
        command: sh -c 'npm i typescript; npm i ts-node -g; npm test'
        restart: always
        environment:
            SERVICE_NAME: ${SERVICE_NAME}
            LOGGER_PORT: ${LOGGER_PORT}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_URL: ${REDIS_URL}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        networks:
            - gateway
    

networks:
    gateway:
